[relabel]
allow-unauthenticated = [
    "S-*", "A-*", "New Content", "Language Cleanup", "Easy", "Formatting", "Enhancement", "Bug",
]

[assign]

[shortcut]

[merge-conflicts]
remove = []
add = ["S-waiting-on-author"]
unless = ["S-blocked", "S-waiting-on-team", "S-waiting-on-review"]
